#!/usr/bin/perl -w

package bs_srcserver_gitonly;

use strict;

sub putinsrcrep {
  my ($projid, $packid, $tmpfile, $filename) = @_;

  open(F, '<', $tmpfile) || die("$tmpfile: $!\n");

  chdir("$srcgitrep/$projid/$packid");            # prepne sa do adresara s repom
  $git_hash = system("git hash-object $tmpfile"); # vypise na stdin hash
  # TODO: pridat ($git_hash, $filename) do $filelist-u XML co pride do funkcie nizsie
  unlink($tmpfile);

  return $git_hash;
}


sub urobcommit {
  my ($cgi, $projid, $packid) = @_; # zoznam suborov (subor,hash) je v $filelist (z PUTu)
  chdir("$srcgitrep/$projid/$packid");
  foreach ($file in $filelist) {
    system("git update-index --cacheinfo 0644 " + $file.git_hash + " " + $file.name); # prida subor do commitu
  }
  system("git commit")
  $hash = system("git log | head -n 1 | cut -f 2 -d ' '")
  return $hash;
}
